---
author: V. Keith Hughitt
date: "`r format(Sys.time(), '%d %B, %Y')`"
params:
  settings: ""
  title: "Similarity of individual co-expression networks"
  version: ""
  analysis_dirname: "02-individual-network-similarity"
title: "`r params$title` (`r params$version`)"
output:
  html_document:
    toc: true
    number_sections: true
  pdf_document:
    toc: true
    number_sections: true
    latex_engine: xelatex
---

```{r load_libraries, message=FALSE}
library(annotables)
library(dplyr)
library(gplots)
library(ggplot2)
library(knitr)
library(readr)
library(RColorBrewer)
library(clusteval)
library(irr)
library(mclust)
library(viridis)

# heatmap font sizes
heatmap_cex <- 0.5
```

```{r child='child/02-indiv-net-similarity-overview.Rmd'}
```

# Setup

```{r child='child/00-shared-setup.Rmd'}
```

```{r settings}
# edge weight quantile cutoff to use when comparing ratio of overlap for top edges
# in each network
EDGE_WEIGHT_QUANTILE_CUTOFF <- 0.90
```

**Load individual networks**

First, we will load the co-expression network ranking from the most recent round of optimization.

```{r compute_enrichment_scores}
networks <- MANUSCRIPT_CONFIG$networks

if (CONFIG$target == 'host') {
    # Host (GO, CPDB, Marbach)
    networks$enrichment_score = as.vector((1/3) * (scale(networks$total_go_pval) +
                                                   scale(networks$total_cpdb_pval) +
                                                   scale(networks$total_marbach_pval)))
} else {
    # Parasite (GO)
    networks$enrichment_score = as.vector(scale(networks$total_go_pval))
}

# add rank column and sort rank
networks = networks %>%
  arrange(desc(enrichment_score))
networks$rank = 1:nrow(networks)
```

```{r select_networks}
# number of networks to compare
num_networks <- min(MANUSCRIPT_CONFIG$num_networks, nrow(networks))

# Get N randomly selected networks
networks <- networks[sample(1:nrow(networks), num_networks), ]

# Get top N highest-scoring networks
#networks <- head(networks %>% arrange(desc(enrichment_score)), num_networks)
```

# Methods & Results

```{r child='child/02-indiv-net-module-similarity.Rmd'}
```

```{r child='child/02-indiv-net-permuted-network-similarity.Rmd'}
```

```{r child='child/02-indiv-net-edge-similarity.Rmd'}
```

# System Information

```{r}
sessionInfo()
```

```{r git_commit}
# manuscript-specific code (https://github.com/elsayed-lab/manuscript-coex-networks)
system('git rev-parse --short HEAD', intern = TRUE)

# shared code (https://github.com/elsayed-lab/manuscript-shared-rnaseq)
system('git --git-dir=$UMD/2015/00-shared/.git rev-parse --short HEAD', intern = TRUE)
```

```{r save_output, include=FALSE}
# Give rmarkdown some time to finish convern and then copy original rmarkdown
# along with output images and HTML to archive location
html_filepath <- file.path(output_prefix, paste0('individual-network-similarity_', MANUSCRIPT_CONFIG$output_prefix, '.html'))
pdf_filepath <- sub('html', 'pdf', html_filepath)

if (opts_knit$get("rmarkdown.pandoc.to") == 'latex') {
    system(sprintf('(sleep 30 && mv 02-individual-network-similarity.pdf %s) &', pdf_filepath))
} else {
    system(sprintf('(sleep 30 && mv 02-individual-network-similarity.html %s) &', html_filepath))
}
```

```{r}
# total running time
Sys.time() - time_start
```

