---
author: V. Keith Hughitt
date: "`r format(Sys.time(), '%d %B, %Y')`"
title: "Host Consensus Network Analysis"
params:
  version: "1.0"
  settings: "settings/host-analysis.Rmd"
  analysis_dirname: "03-host-network-analysis"
output:
  html_document:
    theme: cosmo
    toc: true
    toc_float: true
    number_sections: true
    code_folding: hide
  pdf_document:
    toc: true
    latex_engine: xelatex
---

Methods
=======

Setup
-----

## Setup

```{r child='child/00-shared-setup.Rmd'}
```

```{r load_libraries, message=FALSE}
library('biomaRt')
library('doParallel')
library('dplyr')
library('dynamicTreeCut')
library('flashClust')
library('foreach')
library('ggplot2')
library('goseq')
library('gplots')
library('hpgltools')
library('igraph')
library('knitr')
library('knitcitations')
library('reshape2')
library('readr')
library('preprocessCore')
library('tibble')
library('tools')
library('viridis')
source('../../2015/00-shared/R/annotations.R')
source('../../2015/00-shared/R/count_tables.R')
source('../../2015/00-shared/R/enrichment_analysis.R')
source('../../2015/00-shared/R/util.R')
```

```{r child='../../2015/00-shared/Rmd/init/load_counts.Rmd'}
```

```{r child='../../2015/00-shared/Rmd/init/load_host_annotations.Rmd', eval=CONFIG$target == 'host'}
```

```{r}
# keep a backup of full annotation dataframe
gene_info_orig <- gene_info
```

Load host consensus networks
----------------------------

```{r load_host_nets}
load('output/1.0/02-network-construction/data/adjmat_filtered_hslm-inf.rda')
hslm_inf <- filtered_adjmat

load('output/1.0/02-network-construction/data/adjmat_filtered_hslm-uninf.rda')
hslm_uninf <- filtered_adjmat

load('output/1.0/02-network-construction/data/adjmat_filtered_hstc-inf.rda')
hstc_inf <- filtered_adjmat

load('output/1.0/02-network-construction/data/adjmat_filtered_hstc-uninf.rda')
hstc_uninf <- filtered_adjmat
```

Infected vs. Uninfected Networks
--------------------------------

### Human infected with *L. major*

```{r}
inf <- hslm_inf
uninf <- hslm_uninf

subtitle <- 'Human infected with L. major'

# update figure prefix
opts_chunk$set(fig.path=paste0(output_figprefix, 'hslm-inf-vs-uninf-'))
```

```{r child='child/03-network-setup-inf-vs-uninf.Rmd'}
```

```{r child='child/03-host-analysis-inf-vs-uninf.Rmd'}
```

#### Summary of enrichment results

```{r child='child/00-shared-summary-of-enrichment-results.Rmd'}
```

### Human infected with *T. cruzi*

```{r}
inf   <- hstc_inf
uninf <- hstc_uninf

subtitle <- 'Human infected with T. cruzi'

# update figure prefix
opts_chunk$set(fig.path=paste0(output_figprefix, 'hstc-inf-vs-uninf-'))
```

```{r child='child/03-network-setup-inf-vs-uninf.Rmd'}
```

```{r child='child/03-host-analysis-inf-vs-uninf.Rmd'}
```

#### Summary of enrichment results

```{r child='child/00-shared-summary-of-enrichment-results.Rmd'}
```

Conserved signatures of infection: H. sapiens infected with *L. major* vs. *T. cruzi*
-------------------------------------------------------------------------------------

```{r}
# update figure prefix
opts_chunk$set(fig.path=paste0(output_figprefix, 'hstc_vs_hslm-'))
```

```{r child='child/03-network-setup-hstc-vs-hslm.Rmd'}
```

```{r child='child/03-host-conserved-infection-sig.Rmd'}
```

#### Summary of enrichment results

```{r child='child/00-shared-summary-of-enrichment-results.Rmd'}
```

Save Results
------------

```{r save_output, include=FALSE}
# Give rmarkdown some time to finish convern and then copy original rmarkdown
# along with output images and HTML to archive location
html_filepath <- file.path(output_prefix, paste0(MANUSCRIPT_CONFIG$output_dirname, '.html'))

if (opts_knit$get("rmarkdown.pandoc.to") == 'latex') {
    system(sprintf('(sleep 30 && mv 03-host-network-analysis.pdf %s) &', html_filepath))
} else {
    system(sprintf('(sleep 30 && mv 03-host-network-analysis.html %s) &', html_filepath))
}
```

