---
author: "V. Keith Hughitt"
date: "`r format(Sys.time(), '%d %B, %Y')`"
params:
  analysis_dirname: "05-infected-vs-uninfected"
  settings: ""
  title: ""
  version: ""
title: "`r params$title` (`r params$version`)"
output:
  html_document:
    theme: cosmo
    toc: true
    toc_float: true
    number_sections: true
    code_folding: hide
  pdf_document:
    toc: true
    latex_engine: xelatex
---

### Setup

```{r load_libraries, message=FALSE}
library(biomaRt)
library(doParallel)
library(dynamicTreeCut)
library(flashClust)
library(foreach)
library(goseq)
library(gplots)
library(gridExtra)
library(hpgltools)
library(igraph)
library(knitr)
library(knitcitations)
library(reshape2)
library(rJava)
library(preprocessCore)
library(tools)
library(viridis)
library(xlsx)
library(tidyverse)
source('../../2015/00-shared/R/annotations.R')
source('../../2015/00-shared/R/count_tables.R')
source('../../2015/00-shared/R/enrichment_analysis.R')
source('../../2015/00-shared/R/plots.R')
source('../../2015/00-shared/R/util.R')
source('../../2015/00-shared/R/wgcna.R')
```

```{r child='child/00-shared-setup.Rmd'}
```

```{r child='child/05-infected-vs-uninfected-load-counts.Rmd'}
```

```{r child='../../2015/00-shared/Rmd/init/load_host_annotations.Rmd'}
```

```{r}
# update figure prefix
opts_chunk$set(fig.path=paste0(output_figprefix,
                               paste0(MANUSCRIPT_CONFIG$output_suffix, '-')))
options(digits=4)

# keep a backup of full annotation dataframe
gene_info_orig <- gene_info
```

### Load host consensus networks

```{r load_host_nets}
load(MANUSCRIPT_CONFIG$adjmat_inf)
inf <- adjmat

load(MANUSCRIPT_CONFIG$adjmat_uninf)
uninf <- adjmat
```

### Construct difference network

```{r}
mapping_inf   <- CONFIG_INF$condition_mapping
mapping_uninf <- CONFIG_UNINF$condition_mapping

condition_inf   <- factor(CONFIG_INF$samples[['Condition']])
condition_uninf <- factor(CONFIG_UNINF$samples[['Condition']])

subtitle <- MANUSCRIPT_CONFIG[['subtitle']]

# update figure prefix
opts_chunk$set(fig.path=paste0(output_figprefix,
                               paste0(MANUSCRIPT_CONFIG$output_suffix, '-')))
```

```{r child='child/05-infected-vs-uninfected-setup.Rmd'}
```

```{r child='child/05-infected-vs-uninfected-main.Rmd'}
```

### Summary of enrichment results

```{r child='child/00-shared-summary-of-enrichment-results.Rmd'}
```

### Save Results


```{r child='child/00-shared-save-tables.Rmd'}
```

```{r save_output, include=FALSE}
# Give rmarkdown some time to finish convern and then copy original rmarkdown
# along with output images and HTML to archive location
html_filepath <- file.path(output_prefix, paste0(MANUSCRIPT_CONFIG$output_prefix, '.html'))
pdf_filepath <- file.path(output_prefix, paste0(MANUSCRIPT_CONFIG$output_prefix, '.pdf'))

if (opts_knit$get("rmarkdown.pandoc.to") == 'latex') {
    system(sprintf('(sleep 60 && mv 05-infected-vs-uninfected.pdf %s) &', pdf_filepath))
} else {
    system(sprintf('(sleep 60 && mv 05-infected-vs-uninfected.html %s) &', html_filepath))
}

# free up memory for pandoc
rm(diff)
suppressMessages(gc())
```

