---
author: "V. Keith Hughitt"
date: "`r format(Sys.time(), '%d %B, %Y')`"
title: "Difference Co-expression Network - HsLm vs. HsTc"
params:
  analysis_dirname: "06-conserved-signatures"
  settings: ""
  title: "Difference Networks - Conserved Signatures of Infection (HsLm vs. HsTc)"
  version: "3.0"
output:
  html_document:
    theme: cosmo
    toc: true
    toc_float: true
    number_sections: true
    code_folding: hide
  pdf_document:
    toc: true
    latex_engine: xelatex
---

### Setup

```{r load_libraries, message=FALSE}
library('biomaRt')
library('doParallel')
library('dplyr')
library('dynamicTreeCut')
library('flashClust')
library('foreach')
library('ggplot2')
library('goseq')
library('gplots')
library('gridExtra')
library('hpgltools')
library('igraph')
library('knitr')
library('knitcitations')
library('reshape2')
library('readr')
library('preprocessCore')
library('tibble')
library('tools')
library('viridis')
library('xlsx')
source('../../2015/00-shared/R/annotations.R')
source('../../2015/00-shared/R/count_tables.R')
source('../../2015/00-shared/R/enrichment_analysis.R')
source('../../2015/00-shared/R/plots.R')
source('../../2015/00-shared/R/util.R')
source('../../2015/00-shared/R/wgcna.R')
```

```{r child='child/00-shared-setup.Rmd'}
```

```{r child='child/06-conserved-signature-load-counts.Rmd'}
```

```{r child='../../2015/00-shared/Rmd/init/load_host_annotations.Rmd'}
```

```{r}
# keep a backup of full annotation dataframe
gene_info_orig <- gene_info
```

### Load host consensus networks

```{r load_host_nets}
load(MANUSCRIPT_CONFIG$adjmat_hslm_inf)
hslm_inf <- adjmat

load(MANUSCRIPT_CONFIG$adjmat_hslm_uninf)
hslm_uninf <- adjmat

load(MANUSCRIPT_CONFIG$adjmat_hstc_inf)
hstc_inf <- adjmat

load(MANUSCRIPT_CONFIG$adjmat_hstc_uninf)
hstc_uninf <- adjmat
```

### Construct difference network

```{r}
mapping_hslm_inf   <- CONFIG_HSLM$condition_mapping
mapping_hslm_uninf <- CONFIG_HSLMUI$condition_mapping
mapping_hstc_inf   <- CONFIG_HSTC$condition_mapping
mapping_hstc_uninf <- CONFIG_HSTCUI$condition_mapping

condition_hslm_inf   <- factor(CONFIG_HSLM$samples[['Condition']])
condition_hslm_uninf <- factor(CONFIG_HSLMUI$samples[['Condition']])
condition_hstc_inf   <- factor(CONFIG_HSTC$samples[['Condition']])
condition_hstc_uninf <- factor(CONFIG_HSTCUI$samples[['Condition']])
```

```{r child='child/05-infected-vs-uninfected-setup.Rmd'}
```

```{r child='child/05-infected-vs-uninfected-main.Rmd'}
```

### Summary of enrichment results

```{r child='child/00-shared-summary-of-enrichment-results.Rmd'}
```

### Save Results


```{r child='child/00-shared-save-tables.Rmd'}
```

```{r save_output, include=FALSE}
# Give rmarkdown some time to finish convern and then copy original rmarkdown
# along with output images and HTML to archive location
html_filepath <- file.path(output_prefix, paste0(MANUSCRIPT_CONFIG$output_prefix, '.html'))

if (opts_knit$get("rmarkdown.pandoc.to") == 'latex') {
    system(sprintf('(sleep 30 && mv 05-infected-vs-uninfected.pdf %s) &', html_filepath))
} else {
    system(sprintf('(sleep 30 && mv 05-infected-vs-uninfected.html %s) &', html_filepath))
}
```

