### Summary of enrichment results

Functionally enriched co-expression modules:

```{r table_s1_module_membership}
# all(gene_info$gene_id == gene_tree$labels)                                                                                                                                                                   
# [1] TRUE
table_S1 <- data.frame(gene_id=gene_info$gene_id, 
                       color=module_colors,
                       cluster=module_labels,
                       description=gene_info$description)
```

```{r module_enrichment_overview, results='asis'}
# GO enrichment P-value score
pval_score_go   <- 0
go_terms <- c()

for (module in names(module_go_enrichment)) {
    # over-represented terms with adj. p-val <= 0.05
    mask <- module_go_enrichment[[module]]$over_represented_pvalue_adj <= 0.05

    # -log10pvals (limit to 1E-10)
    pvals <- module_go_enrichment[[module]]$over_represented_pvalue_adj[mask]
    pval_score_go <- pval_score_go + sum(-log10(pmax(pvals, 10^-10)))

    go_terms <- c(go_terms, module_go_enrichment[[module]]$category[mask])
}

# KEGG enrichment P-value score
pval_score_kegg <- 0
kegg_pathways <- c()

for (module in names(module_kegg_enrichment)) {
    # over-represented terms with adj. p-val <= 0.05
    mask <- module_kegg_enrichment[[module]]$over_represented_pvalue_adj <= 0.05

    # -log10pvals (limit to 1E-10)
    pvals <- module_kegg_enrichment[[module]]$over_represented_pvalue_adj[mask]
    pval_score_kegg <- pval_score_kegg + sum(-log10(pmax(pvals, 10^-10)))

    kegg_pathways <- c(kegg_pathways, module_kegg_enrichment[[module]]$category[mask])
}

# CPDB / Marbach TF enrichment P-value score
if (CONFIG$target == 'host') {
    pval_score_coreg <- 0
    pval_score_cpdb  <- 0
    tfs           <- c()
    cpdb_pathways <- c()

    # CPDB
    for (module in names(module_cpdb_enrichment)) {
        # over-represented terms with adj. p-val <= 0.05
        mask <- module_cpdb_enrichment[[module]]$over_represented_pvalue_adj <= 0.05

        # -log10pvals (limit to 1E-10)
        pvals <- module_cpdb_enrichment[[module]]$over_represented_pvalue_adj[mask]
        pval_score_cpdb <- pval_score_cpdb + sum(-log10(pmax(pvals, 10^-10)))

        cpdb_pathways <- c(cpdb_pathways, module_go_enrichment[[module]]$category[mask])
    }

    # Marbach 2016
    for (module in names(module_coreg_enrichment)) {
        # over-represented terms with adj. p-val <= 0.05
        mask <- module_coreg_enrichment[[module]]$over_represented_pvalue_adj <= 0.05

        # -log10pvals (limit to 1E-10)
        pvals <- module_coreg_enrichment[[module]]$over_represented_pvalue_adj[mask]
        pval_score_coreg <- pval_score_coreg + sum(-log10(pmax(pvals, 10^-10)))

        tfs <- c(tfs, module_coreg_enrichment[[module]]$category[mask])
    }
}
```

```{r table_S2_enriched_network_modules}
table_S2 <- module_sizes %>%
    dplyr::rename(Module=module_id)

go_stats <- sapply(module_go_enrichment, nrow) %>%
    as.data.frame %>%
    rownames_to_column %>%
    setNames(c('Module', 'Num Enriched GO Terms'))
table_S2 <- merge(table_S2, go_stats, by='Module')

kegg_stats <- sapply(module_kegg_enrichment, nrow) %>%
    as.data.frame %>%
    rownames_to_column %>%
    setNames(c('Module', 'Num Enriched KEGG Pathways'))
table_S2 <- merge(table_S2, kegg_stats, by='Module')

if (CONFIG$target == 'host') {
    tf_stats <- sapply(module_coreg_enrichment, nrow) %>%
        as.data.frame %>%
        rownames_to_column %>%
        setNames(c('Module', 'Num Enriched TF Regulon Genes'))
    table_S2 <- merge(table_S2, tf_stats, by='Module')
}

if (CONFIG$target == 'pathogen') {
    enriched_secreted <- secreted_freqs %>% 
        mutate(num_enriched=ifelse(p.value.adj < 0.05, num_secreted, 0)) %>%
        select(Module=module, `Num Secreted`=num_enriched)
    table_S2 <- merge(table_S2, enriched_secreted, by='Module')

    enriched_membrane <- membrane_freqs %>% 
        mutate(num_enriched=ifelse(p.value.adj < 0.05, num_membrane, 0)) %>%
        select(Module=module, `Num Transmembrane`=num_enriched)
    table_S2 <- merge(table_S2, enriched_membrane, by='Module')

    enriched_gpi <- gpi_anchored_freqs %>% 
        mutate(num_enriched=ifelse(p.value.adj < 0.05, num_gpi, 0)) %>%
        select(Module=module, `Num GPI-Anchored`=num_enriched)
    table_S2 <- merge(table_S2, enriched_gpi, by='Module')
}

# show modules with functional enrichment, in order of # enriched annotations
mask <- rowSums(table_S2[,3:ncol(table_S2)]) > 0
num_annot <- rowSums(table_S2[mask,] %>% select(-Module, -num_genes))
```

```{r results='asis'}
# common enrichment
template <- paste("- Number of genes: %d",
                  "- Number of modules: %d",
                  "- Total functionally-enriched modules: %d / %d",
                  "- Total GO enrichment P-value score: %0.1f (%d unique terms)", 
                  "- Total KEGG enrichment P-value score: %0.1f (%d unique pathways)\n", sep='\n')

# host-specific 
if (CONFIG$target == 'host') {
    template <- paste0(template, 
                      "- Total CPDB enrichment P-value score: %0.1f (%d unique pathways)\n",
                      "- Total Marbach TF enrichment P-value score: %0.1f (%d unique TF's)\n")
    cat(sprintf(template, 
                nrow(filtered_adjmat), num_modules,
                nrow(table_S2[mask,]), nrow(module_sizes),
                pval_score_go, length(unique(go_terms)),
                pval_score_kegg, length(unique(kegg_pathways)),
                pval_score_cpdb, length(unique(cpdb_pathways)),
                pval_score_coreg, length(unique(tfs))))
} else {
    # parasite (GO/KEGG/Secreted/TM/GPI)
    template <- paste0(template, 
                      "- Number of modules enriched for secreted proteins: %d (%d secreted proteins)\n",
                      "- Number of modules enriched for transmembrane proteins: %d (%d TM proteins)\n",
                      "- Number of modules enriched for GPI-anchored proteins: %d (%d GPI-anchored proteins)\n")
    cat(sprintf(template, 
                nrow(filtered_adjmat), num_modules,
                nrow(table_S2[mask,]), nrow(module_sizes),
                pval_score_go, length(unique(go_terms)),
                pval_score_kegg, length(unique(kegg_pathways)),
                sum(enriched_secreted$`Num Secreted` > 0),
                sum(enriched_secreted$`Num Secreted`),
                sum(enriched_membrane$`Num Transmembrane` > 0),
                sum(enriched_membrane$`Num Transmembrane`),
                sum(enriched_gpi$`Num GPI-Anchored` > 0),
                sum(enriched_gpi$`Num GPI-Anchored`)))
}
```

```{r table_S2_output, results='asis'}
table_S2[mask,] %>% 
    arrange(desc(num_annot)) %>%
    filter(Module != 'grey') %>%
    xkable
```

```{r table_S3}
# save enrichment results as tabular output;
# list of tables will be saved as an XLS file
table_S3 <- list()

# iterate over enrichment results
for (enrichment_result in ls()[grepl('module_[a-z]*_enrichment', ls())]) {
    # enrichment type ("go", "kegg", etc.)
    label <- unlist(strsplit(enrichment_result, "_"))[2]
    table_S3[[label]] <- do.call("rbind", get(enrichment_result))
}
```

```{r save_enrichment_table}
# list of tables will be saved as an XLS file
table_01 <- list()

# iterate over enrichment results
for (enrichment_result in ls()[grepl('module_[a-z]*_enrichment', ls())]) {
    # enrichment type ("go", "kegg", etc.)
    label <- unlist(strsplit(enrichment_result, "_"))[2]
    table_01[[label]] <- do.call("rbind", get(enrichment_result))
}


# output filepath
output_filename <- sprintf('enrichment_results_%s.xls', output_suffix)
xls_filepath <- file.path('..', output_tabledir, output_filename)

sheet_names <- names(table_01)

write.xlsx(as.data.frame(table_01[[sheet_names[1]]]), file=xls_filepath,
            sheetName=sheet_names[1], row.names=FALSE)

for (sheet in sheet_names[2:length(table_01)]) {
    # free up Java memory on each loop iteration
    # http://stackoverflow.com/questions/21937640/handling-java-lang-outofmemoryerror-when-writing-to-excel-from-r
    .jcall("java/lang/System", method = "gc")

    if (nrow(table_01[[sheet]]) > 0) {
        write.xlsx(as.data.frame(table_01[[sheet]]), file=xls_filepath,
                    sheetName=sheet, row.names=FALSE)
    }
}
```
