```{r parameters_to_plot, echo=FALSE}
plot_nettype   <- 'network_type'        %in% colnames(df) && length(unique(df$network_type)) > 1
plot_lowcount  <- 'low_count_threshold' %in% colnames(df) && length(unique(df$low_count_threshold)) > 1
plot_cpm       <- 'cpm_transform'       %in% colnames(df) && length(unique(df$cpm_transform)) > 1
plot_log2      <- 'log2_transform'      %in% colnames(df) && length(unique(df$log2_transform)) > 1
plot_qnorm     <- 'quantile_normalize'  %in% colnames(df) && length(unique(df$quantile_normalize)) > 1
plot_batch_adj <- 'batch_adjustment'    %in% colnames(df) && length(unique(df$batch_adjustment)) > 1
plot_simmeas   <- 'similarity_measure'  %in% colnames(df) && length(unique(df$similarity_measure)) > 1
plot_adjpow    <- 'adj_power'           %in% colnames(df) && length(unique(df$adj_power)) > 1
plot_tom       <- 'topological_overlap' %in% colnames(df) && length(unique(df$topological_overlap)) > 1
```

**Similarity Measure**

<!-- Similarity Measure -->
```{r similarity_measure, results='asis', fig.height=fig_height, out.width=out_width, out.height=out_height, echo=FALSE}
ggplot(df, aes(similarity_measure, enrichment_score)) + 
    geom_boxplot(aes(fill=factor(similarity_measure))) +
    theme_bw_high_res() +
    xlab('Similarity Measure') + ylab('Enrichment score') +
    theme(text=element_text(size=14)) +
    #theme(text=element_text(size=16),
    #      axis.text=element_text(size=16),
    #      axis.text.x=element_text(angle=90, hjust=1),
    #      legend.text=element_text(size=16),
    #      plot.margin=unit(c(0.5, 0.5, 0.5, 0.5),"cm")) +
    guides(guide_legend(title="Similarity Measure")) +
    scale_fill_discrete(name='Similarity Measure')
```

**Log2, CPM, Quantile Normalization**

<!-- Log2, CPM, Qnorm -->
```{r log2_cpm_qnorm}
# log2
plt1 <- ggplot(df, aes(log2_transform, enrichment_score)) + 
            geom_boxplot(aes(fill=factor(log2_transform))) +
            theme_bw_high_res() +
            theme(legend.position="none",
                  axis.text=element_text(size=10)) +
            xlab('Log2-transformation') + 
            ylab('Enrichment score')

# cpm
plt2 <- ggplot(df, aes(cpm_transform, enrichment_score)) + 
            geom_boxplot(aes(fill=factor(cpm_transform))) +
            scale_colour_manual(values=ggplot_discrete_colors) + 
            theme_bw_high_res() +
            theme(legend.position="none",
                  axis.text=element_text(size=9)) +
            xlab('CPM-transformation') + 
            ylab('Enrichment score')

# qnorm
plt3 <- ggplot(df, aes(quantile_normalize, enrichment_score)) + 
            geom_boxplot(aes(fill=factor(quantile_normalize))) +
            theme_bw_high_res() +
            theme(legend.position="none",
                  axis.text=element_text(size=8)) +
            xlab('Quantile normalization') + 
            ylab('Enrichment score')

grid.arrange(plt1, plt2, plt3, ncol=2)
```

**Log2, CPM, Quantile Normalization (by similarity measure)**

<!-- Log2, CPM, Qnorm (by similarity measure) -->
```{r log2_cpm_qnorm_by_sim}
# log2, grouped by similarity measure
plt1 <- ggplot(df, aes(log2_transform, enrichment_score)) + 
            geom_boxplot(aes(fill=factor(similarity_measure))) +
            theme_bw_high_res() +
            theme(legend.position="none") +
            xlab('Log2-transformation') + 
            ylab('Enrichment score')

# cpm, grouped by similarity measure
plt2 <- ggplot(df, aes(cpm_transform, enrichment_score)) + 
            geom_boxplot(aes(fill=factor(similarity_measure))) +
            scale_colour_manual(values=ggplot_discrete_colors) + 
            theme_bw_high_res() +
            theme(legend.position="none") +
            xlab('CPM-transformation') + 
            ylab('Enrichment score')

# qnorm, grouped by similarity measure
plt3 <- ggplot(df, aes(quantile_normalize, enrichment_score)) + 
            geom_boxplot(aes(fill=factor(similarity_measure))) +
            theme_bw_high_res() +
            theme(legend.position="none") +
            xlab('Quantile normalization') + 
            ylab('Enrichment score')

grid.arrange(plt1, plt2, plt3, ncol=2)
```

<!-- Batch Adjustment -->
```{r batch_adjustment, results='asis', fig.height=fig_height, out.width=out_width, out.height=out_height, echo=FALSE, include=plot_batch_adj, eval=plot_batch_adj}
cat('\n**Batch adjustment**\n\n')

ggplot(df, aes(batch_adjustment, enrichment_score)) + 
    geom_boxplot(aes(fill=factor(similarity_measure))) +
    guides(guide_legend(title="Similarity Measure")) +
    theme_bw_high_res() +
    xlab('Batch Adjustment Method') + ylab('Enrichment score')

ggplot(df, aes(batch_adjustment, enrichment_score)) + 
    geom_boxplot(aes(fill=factor(batch_adjustment))) +
    guides(guide_legend(title="Similarity Measure")) +
    theme_bw_high_res() +
    xlab('Batch Adjustment Method') + ylab('Enrichment score') +
    guides(guide_legend(FALSE))
```

<!-- Adjacency Power -->
```{r adjpower, results='asis', fig.height=fig_height, out.width=out_width, out.height=out_height, echo=FALSE}
cat('\n**Adjacency power**\n\n')
ggplot(df, aes(factor(adj_power), enrichment_score)) + 
    geom_boxplot() +
    theme_bw_high_res() +
    xlab('Adjacency power') + ylab('Enrichment score')
```

<!-- Network Type (Signed vs. Unsigned) -->
```{r network_type, results='asis', fig.height=fig_height, out.width=out_width, out.height=out_height, echo=FALSE, include=plot_nettype, eval=plot_nettype}
cat('\n**Network Type**\n\n')

# network type
ggplot(df, aes(network_type, enrichment_score)) + 
    geom_boxplot(aes(fill=factor(network_type))) +
    scale_colour_manual(values=ggplot_discrete_colors) + 
    theme_bw_high_res() +
    xlab('Network Type') + ylab('Enrichment score') +
    guides(guide_legend(FALSE))

# network type, grouped by similarity measure
ggplot(df, aes(network_type, enrichment_score)) + 
    geom_boxplot(aes(fill=factor(similarity_measure))) +
    scale_colour_manual(values=ggplot_discrete_colors) + 
    guides(guide_legend(title="Similarity Measure")) +
    theme_bw_high_res() +
    xlab('Network Type') + ylab('Enrichment score')
```

<!-- Topological Overlap -->
```{r topological_overlap, results='asis', fig.height=fig_height, out.width=out_width, out.height=out_height, echo=FALSE, include=plot_tom, eval=plot_tom}
cat('\n**Topological overlap**\n\n')
ggplot(df, aes(topological_overlap, enrichment_score)) + 
    geom_boxplot(aes(fill=factor(similarity_measure))) +
    guides(guide_legend(title="Similarity Measure")) +
    theme_bw_high_res() +
    xlab('Topological overlap') + ylab('Enrichment score')
ggplot(df, aes(topological_overlap, enrichment_score)) + 
    geom_boxplot(aes(fill=factor(topological_overlap))) +
    guides(guide_legend(title="Similarity Measure")) +
    theme_bw_high_res() +
    xlab('Topological overlap') + ylab('Enrichment score') +
    guides(guide_legend(FALSE))
```

<!-- Correlation between functional and TF regulon enrichment -->
```{r function_coreg_correlation, results='asis', fig.height=3}
plts <- list()

if ('total_marbach_pval' %in% colnames(df)) {
    # GO correlation
    go_tf_cor <- cor(df$total_go_pval, df$total_marbach_pval)

    # position for correlation score text
    #xpos <- 0.90 * max(df$total_go_pval)
    xpos <- min(df$total_go_pval) + 0.15 * max(df$total_go_pval)
    ypos <- 0.95 * max(df$total_marbach_pval)

    cat(sprintf("- GO vs. TF Enrichment Score Pearson correlation: %0.2f\n", go_tf_cor))

    plts[[1]] <- ggplot(aes(x=total_go_pval, y=total_marbach_pval), data=df) + 
        geom_point(size=0.5) + 
        geom_smooth(method='lm') +
        annotate("text", x=xpos, y=ypos, parse=TRUE, color='red',
                 label=sprintf("paste(italic(r), \" = %0.2f\")", go_tf_cor)) +
        coord_cartesian(xlim=c(min(df$total_go_pval) - 15, max(df$total_go_pval) + 30), 
                        ylim=c(min(df$total_marbach_pval) - 15, max(df$total_marbach_pval) + 15), 
                        expand=FALSE) +
        theme_bw_high_res() +
        xlab("GO Enrichment Score") +
        ylab("TF-regulon Enrichment Score")

    cpdb_tf_cor <- cor(df$total_cpdb_pval, df$total_marbach_pval)
    
    #xpos <- 0.90 * max(df$total_cpdb_pval)
    xpos <- min(df$total_cpdb_pval) + 0.15 * max(df$total_cpdb_pval)
    ypos <- 0.95 * max(df$total_marbach_pval) 

    # CPDB correlation
    cat(sprintf("- CPDB vs. TF Enrichment Score Pearson Correlation: %0.2f\n\n", cpdb_tf_cor))

    plts[[2]] <- ggplot(aes(x=total_cpdb_pval, y=total_marbach_pval), data=df) + 
        geom_point(size=0.5) + 
        geom_smooth(method='lm') +
        annotate("text", x=xpos, y=ypos, parse=TRUE, color='red',
                 label=sprintf("paste(italic(r), \" = %0.2f\")", cpdb_tf_cor)) +
        coord_cartesian(xlim=c(min(df$total_cpdb_pval) - 15, max(df$total_cpdb_pval) + 30), 
                        ylim=c(min(df$total_marbach_pval) - 15, max(df$total_marbach_pval) + 30), 
                        expand=FALSE) +
        theme_bw_high_res() +
        theme(axis.title.y=element_blank()) +
        xlab("CPDB Enrichment Score")
}

if (length(plts) > 0) {
    grid.arrange(grobs=plts, ncol=2)
}
```

<!-- Correlation between functional and TF regulon enrichment (pval scores) -->
```{r, function_coreg_correlation_pval_scores, results='asis', fig.height=3}
plts <- list()

if ('total_marbach_pval' %in% colnames(df)) {
    go_tf_cor <- cor(df$total_go_pval, df$total_marbach_pval)
    cat(sprintf("- GO vs. TF Pearson correlation (P-value score): %0.2f\n", go_tf_cor))

    # position for correlation score text
    #xpos <- 0.90 * max(df$total_go_pval)
    xpos <- min(df$total_go_pval) + 0.15 * max(df$total_go_pval)
    ypos <- 0.95 * max(df$total_marbach_pval)
    
    plts[['marbach']] <- ggplot(aes(x=total_go_pval, y=total_marbach_pval), data=df) + 
        geom_point(size=0.5) + 
        geom_smooth(method='lm') +
        annotate("text", x=xpos, y=ypos, parse=TRUE, color='red',
                 label=sprintf("paste(italic(r), \" = %0.2f\")", go_tf_cor)) +
        theme_bw_high_res() +
        xlab("GO Enrichment") +
        ylab("TF regulon enrichment") +
        coord_cartesian(xlim=c(min(df$total_go_pval) - 50, max(df$total_go_pval) + 50), 
                        ylim=c(min(df$total_marbach_pval) - 30, max(df$total_marbach_pval) + 30), 
                        expand=FALSE)

    cpdb_tf_cor <- cor(df$total_cpdb_pval, df$total_marbach_pval)
    cat(sprintf("- CPDB vs. TF Pearson correlation (P-value score): %0.2f\n\n", cpdb_tf_cor))

    #xpos <- 0.90 * max(df$total_cpdb_pval)
    xpos <- min(df$total_cpdb_pval) + 0.15 * max(df$total_cpdb_pval)
    ypos <- 0.95 * max(df$total_marbach_pval)

    plts[['cpdb']] <- ggplot(aes(x=total_cpdb_pval, y=total_marbach_pval), data=df) + 
        geom_point(size=0.5) + 
        geom_smooth(method='lm') +
        annotate("text", x=xpos, y=ypos, parse=TRUE, color='red',
                 label=sprintf("paste(italic(r), \" = %0.2f\")", cpdb_tf_cor)) +
        theme_bw_high_res() +
        theme(axis.title.y=element_blank()) +
        coord_cartesian(xlim=c(min(df$total_cpdb_pval) - 50, max(df$total_cpdb_pval) + 50), 
                        ylim=c(min(df$total_marbach_pval) - 30, max(df$total_marbach_pval) + 30), 
                        expand=FALSE) +
        xlab("CPDB enrichment")
}

if (length(plts) > 0) {
    grid.arrange(grobs=plts, ncol=2)
}
```

**Number of modules vs. enrichment score**

```{r num_modules_vs_enrichment_score}
ggplot(df, aes(x=num_modules, y=enrichment_score)) +
    geom_point() + 
    theme_bw_high_res() +
    xlab("# Modules") +
    ylab("Enrichment Score")
```

```{r, include=FALSE, eval=FALSE}
# Median size
# Nothing special here either..
ggplot(df, aes(x=med_module_size, y=enrichment_score)) +
    geom_point() + 
    theme_bw_high_res() +
    xlab("Median Module Size") +
    ylab("Enrichment Score")
```


```{r num_modules_vs_enrichment_score, results='asis', eval='total_edge_weight' %in% colnames(df)}
cat('\n\n**Total network edge weight vs. enrichment score**\n\n')
ggplot(df, aes(x=total_edge_weight, y=enrichment_score, color=factor(adj_power))) +
    geom_point() + 
    theme_bw_high_res() +
    xlab("Sum(edge weights)") +
    ylab("Enrichment Score")
```
