```{r detect_consensus_net_modules}
# TODO: reconsider how best to go from aggregate adjacency matrix to distance
# matrix
distmat <- 1 - (filtered_adjmat / max(filtered_adjmat))

gene_tree <- flashClust(as.dist(distmat), method="average")
gene_tree$height <- round(gene_tree$height, 6)

module_labels <- cutreeDynamicTree(dendro=gene_tree, deepSplit=FALSE, minModuleSize=10)

num_labels <- length(unique(module_labels))
pal <- c('grey', substring(rainbow(num_labels), 1, 7))
module_colors <- (pal[module_labels + 1])
```

```{r module_sizes}
# create a mapping from module id to number of genes for later use
module_sizes <- setNames(as.data.frame(module_colors), 'module_id') %>% 
    group_by(module_id) %>% 
    summarize(num_genes=n())

num_modules <- length(unique(module_colors))
```

```{r module_stats, results='asis'}
cat(sprintf("- Number of modules: %d\n", num_modules))
cat(sprintf("- Median module size: %0.1f\n", median(module_sizes$num_genes)))
cat(sprintf("- Largest module size: %d\n", max(module_sizes$num_genes)))
```
