### Jaccard Index (permuted modules)

To get a sense for how similar two completely random networks with similar
module sizes and distributions to what we have observed, we will perform a
similar comparison that what was done above, except that the genes in each
module will be randomized before comparison.

```{r random_network_similarity, results='asis', message=FALSE, cache = CONFIG$use_cache, autodep=TRUE}
random_output <- matrix(nrow=num_networks, ncol=num_networks)
colnames(random_output) <- rownames(random_output) <- paste0("network_", networks$id)

# Iterate over top hits and construct a similarity matrix
for (i in 1:nrow(networks)) {
    id_a <- networks$id[i]
    file_a <- sprintf("%d.RData", id_a)
    load(file.path(MANUSCRIPT_CONFIG$input_dir, file_a))
    mapping_a <- module_mapping

    index_a <- paste0("network_", id_a)

    # randomize module assignments
    mapping_a$color <- sample(mapping_a$color)

    # network b
    for (j in 1:i) {
        id_b <- networks$id[j]
        message(sprintf("...Comparing %s vs. %s", id_a, id_b))

        index_b <- paste0("network_", id_b)

        # set diagonal to 1
        if (id_a == id_b) {
            similarity <- 1
        } else {
            # load network b
            file_b <- sprintf("%d.RData", id_b)
            load(file.path(MANUSCRIPT_CONFIG$input_dir, file_b))
            mapping_b <- module_mapping

            # limit to genes in both networks
            mapping_a <- mapping_a[mapping_a$gene_id %in% mapping_b$gene_id,]
            mapping_b <- mapping_b[mapping_b$gene_id %in% mapping_a$gene_id,]

            # randomize module assignments
            mapping_b$color <- sample(mapping_b$color)

            similarity <- cluster_similarity(as.numeric(factor(mapping_a$color)),
                                             as.numeric(factor(mapping_b$color)),
                                             similarity='jaccard')

        }
        # store results
        random_output[index_a, index_b] <- random_output[index_b, index_a] <- similarity
    }
}

# Set diagonal to maximum of off-diagonal values to increase dynamic range of
# color scale
diag(random_output) <- 0
diag(random_output) <- max(random_output)
```

```{r results='asis'}
cat(sprintf("- Min: %0.2f\n", min(random_output[upper.tri(random_output)])))
cat(sprintf("- Max: %0.2f\n", max(random_output[upper.tri(random_output)])))
cat(sprintf("- Median: %0.2f\n\n", median(random_output[upper.tri(random_output)])))
```

```{r similarity_plot_permuted, cache=TRUE, autodep=TRUE}
heatmap.2(random_output, trace='none', dendrogram='row', margin=c(4,4),
          cexRow=heatmap_cex, cexCol=heatmap_cex, col='plasma',
          key.title=NA, key.xlab='Jaccard Index',
          symbreaks=FALSE, symkey=FALSE)
```

