```{r filter_counts_and_annotations}
count_table <- count_table[rownames(count_table) %in%
                           rownames(filtered_adjmat),]
gene_info <- gene_info %>% filter(gene_id %in% rownames(filtered_adjmat))
```

```{r child='../../../2015/00-shared/Rmd/init/create_expression_set.Rmd'}
```

##### Coarse-grained co-expression network module expression

```{r transformed_counts}
# cpm-transform raw counts
cpm_counts <- sweep(count_table, 2, colSums(count_table), '/') * 1E6
log2cpm_counts <- log2(cpm_counts + 1)

# create a coarse-scale clustering
large_scale_labels <- cutreeDynamicTree(dendro=gene_tree, minModuleSize=100,
                                        deepSplit=FALSE)

# convert module labels to colors
large_scale_module_colors <- labels2colors(large_scale_labels)
```

#### Large-scale module expression (Log2-CPM averages)

```{r figure_X3, results='asis', fig.width=1080/192, fig.height=1080/192}
# average expression profiles for each module
module_averages <- get_module_averages(log2cpm_counts,
                                       large_scale_module_colors, method=median)
combined_module_counts <- combine_replicates(module_averages, condition)

# convert to long
condition_mapping <- data.frame(long=as.character(unique(condition)),
                                short=as.character(unique(condition)))

module_averages_long <- melt_counts(combined_module_counts, condition_mapping)
colnames(module_averages_long) <- c('module', 'condition', 'expression')

# colormap
cmap <- as.character(unique(module_averages_long$module))

# module gene counts
mod_counts <- setNames(tbl_df(table(large_scale_module_colors)), c('color', 'n'))
plot_labels <- sprintf("%s (n=%d)", cmap, mod_counts$n[match(cmap, mod_counts$color)])

# large scale clusters
ggplot(data=module_averages_long,
    aes(x=condition, y=expression, group=module, color=module)) +
    geom_line(size=I(2)) + 
    scale_colour_manual(labels=plot_labels, values=cmap) +
    ggtitle("Module Average Log2-CPM Expression Profiles") +
    xlab("Time (hours)") +
    ylab("Expression level (log2-CPM)") +
    theme(axis.text=element_text(colour="#333333"),
          axis.text.x=element_text(angle=90, hjust=1, vjust=0.5, size=16))
```

```{r expression_profiles, message=FALSE, warning=FALSE, fig.width=18, dpi=96, results='hide'}
# long version of counts
combined_gene_counts <- combine_replicates(log2cpm_counts, condition)

#counts_long <- cbind(gene_id=rownames(count_table), log2cpm_counts)
#counts_long <- melt(counts_long, id.vars='gene_id')
counts_long <- melt(combined_gene_counts, id.vars='row.names')

names(counts_long) <- c('gene_id', 'condition', 'expression')

# If non-numeric conditions (e.g. 'procyclic') are included, convert to
# factor and reorder levels of dataframe for better plotting
if (!is.numeric(counts_long$condition)) {
    counts_long$condition <- factor(counts_long$condition)
}

counts_long <- cbind(counts_long, cluster=as.factor(module_colors))

module_order <- unique(module_colors[gene_tree$order])
module_expression_profile_plot(counts_long, module_colors, module_order,
                               modules_per_plot=4, ncols=2)
```
