## Overview

```{r results='asis'}
if (CONFIG$target == 'host' && CONFIG$host == 'H. sapiens') {
    # GO, KEGG, CPDB, TFs
    dat <- data.frame(
        cutoff_quantile=quantile_cutoffs,
        cutoff=cutoffs,
        num_modules,
        num_genes=genes_passing,
        median_module_size=median_module_sizes,
        largest_module_size=largest_module_sizes,
        total_go_pvals,
        total_kegg_pvals,
        total_cpdb_pvals,
        total_tf_pvals,
        num_go_enriched_modules,
        num_kegg_enriched_modules,
        num_tf_enriched_modules
    ) %>% mutate(
        `Ratio GO-enriched modules`=num_go_enriched_modules/num_modules,
        `Ratio KEGG-enriched modules`=num_kegg_enriched_modules/num_modules,
        `Ratio CPDB-enriched modules`=num_cpdb_enriched_modules/num_modules,
        `Ratio TF-enriched modules`=num_tf_enriched_modules/num_modules,
        `GO enrichment per gene`=total_go_pvals/num_genes,
        `KEGG enrichment per gene`=total_kegg_pvals/num_genes,
        `CPDB enrichment per gene`=total_cpdb_pvals/num_genes,
        `TF enrichment per gene`=total_tf_pvals/num_genes
    ) %>% dplyr::rename(
        `GO enrichment -log10(p-val) score`=total_go_pvals,
        `KEGG enrichment -log10(p-val) score`=total_kegg_pvals,
        `CPDB enrichment -log10(p-val) score`=total_cpdb_pvals,
        `TF enrichment -log10(p-val) score`=total_tf_pvals
    )
} else {
    # GO, KEGG
    dat <- data.frame(
        cutoff_quantile=quantile_cutoffs,
        cutoff=cutoffs,
        num_modules,
        num_genes=genes_passing,
        median_module_size=median_module_sizes,
        largest_module_size=largest_module_sizes,
        total_go_pvals,
        total_kegg_pvals,
        num_go_enriched_modules,
        num_kegg_enriched_modules
    ) %>% mutate(
        `Ratio GO-enriched modules`=num_go_enriched_modules/num_modules,
        `Ratio KEGG-enriched modules`=num_kegg_enriched_modules/num_modules,
        `GO enrichment per gene`=total_go_pvals/num_genes,
        `KEGG enrichment per gene`=total_kegg_pvals/num_genes,
    ) %>% dplyr::rename(
        `GO enrichment -log10(p-val) score`=total_go_pvals,
        `KEGG enrichment -log10(p-val) score`=total_kegg_pvals
    )
}

datatable(dat)
```

## -log10(Adj. P-value) totals

```{r pval_totals, fig.width=1600/300, fig.height=1080/300}
dat_pval_scores <- dat %>%
    select(cutoff_quantile, ends_with('score')) %>%
    melt(id.vars='cutoff_quantile', variable.name='type',
         value.name='pvalue_totals')

ggplot(dat_pval_scores, aes(x=cutoff_quantile, y=pvalue_totals, color=type)) +
    geom_line() +
    #geom_vline(xintercept=MANUSCRIPT_CONFIG$quantile_cutoff, linetype='dashed', color='red') +
    theme_bw_high_res() +
    theme(legend.text=element_text(size=8)) +
    xlab('Edge Weight Cutoff Percentile') + ylab('Total -log10(Adj. P-values)') +
    ggtitle('Total -log10(Adj. P-values) vs. Edge Weight Cutoff')
```

## Ratio of enrichment score to number of genes

```{r ratio_enrichment_to_num_genes, fig.width=1600/300, fig.height=1080/300}
# sum(-log10(adj.p.val)) over # genes vs. cutoff
dat_ratio_enrichment <- dat %>%
    select(cutoff_quantile, ends_with('per gene')) %>%
    melt(id.vars='cutoff_quantile', variable.name='type',
         value.name='ratio_enrichment_to_num_genes')

ggplot(dat_ratio_enrichment, aes(x=cutoff_quantile, y=ratio_enrichment_to_num_genes, color=type)) +
    geom_line() +
    #geom_vline(xintercept=MANUSCRIPT_CONFIG$quantile_cutoff, linetype='dashed', color='red') +
    theme_bw_high_res() +
    theme(plot.title=element_text(margin=unit(c(0, 0, 3, 0), "mm"), size=10)) +
    xlab('Edge Weight Cutoff Percentile') + ylab('Ratio Enrichment to Number of Genes') +
    ggtitle('Ratio of Enrichment to Number of Genes vs. Edge Weight Cutoff')
```

