#### Infected vs. Uninfected Difference Matrix

```{r difference_heatmap, results='asis'}
diff <- inf - uninf

# sub-sample to speed up and better fit in display
ind <- sample(1:nrow(diff), 250)

# with legend
heatmap.2(diff[ind, ind], trace='none', dendrogram='row', labRow=FALSE, labCol=FALSE,
          col='plasma', main=sprintf('Difference Network Adjacency Matrix:\n%s', subtitle),
          margin=c(6, 6), xlab='Gene', ylab='Gene', density='none',
          key.title='', key.ylab='', keysize=2,
          key.xlab='Edge Weight\n (Infected - Uninfected)')

# without legend
heatmap.2(diff[ind, ind], trace='none', dendrogram='row', labRow=FALSE, labCol=FALSE,
          col='plasma', margin=c(6, 6),  key=FALSE)

# edge weight range
cat(sprintf('\n- Minimum edge weight: %0.3f\n', min(diff)))
cat(sprintf('\n- Maximum edge weight: %0.3f\n', max(diff)))
```

```{r diff_matrix_clustering}
# convert to distance matrix and perform hierarchical clustering
# take absolute value of difference adjacency matrix; sets of genes which are
# all changing direction together, will still be separated out
distmat <- (1 + diff) / 2

gene_tree <- flashClust(as.dist(distmat), method="average")
gene_tree$height <- round(gene_tree$height, 6)

# perform dynamic tree-cut based clustering
module_labels <- cutreeDynamicTree(dendro=gene_tree, deepSplit=FALSE, minModuleSize=10)

num_labels <- length(unique(module_labels))
pal <- c('grey', substring(rainbow(num_labels), 1, 7))
module_colors <- (pal[module_labels + 1])

module_mapping <- tbl_df(cbind(gene_id=rownames(diff), module=module_colors))

# create a mapping from module id to number of genes for later use
module_sizes <- setNames(as.data.frame(module_colors), 'module_id') %>% 
    group_by(module_id) %>% 
    summarize(num_genes=n())

num_modules <- length(unique(module_colors))
```

```{r generate_long_counts}
# cpm-transform raw counts (infected)
cpm_counts_inf <- sweep(counts_inf, 2, colSums(counts_inf), '/') * 1E6
cpm_counts_inf <- cpm_counts_inf[rownames(cpm_counts_inf) %in% gene_tree$labels,]

log2cpm_counts_inf <- log2(cpm_counts_inf + 1)

combined_gene_counts_inf <- combine_replicates(log2cpm_counts_inf,
                                               condition_inf)
counts_long_inf <- melt(combined_gene_counts_inf, id.vars='row.names')
names(counts_long_inf) <- c('gene_id', 'condition', 'expression')

# Human-readable labels
counts_long_inf$condition <- mapping_inf$to[match(counts_long_inf$condition, mapping_inf$from)]

# If non-numeric conditions (e.g. 'procyclic') are included, convert to
# factor and reorder levels of dataframe for better plotting
#if (!is.numeric(counts_long$condition)) {
#    counts_long$condition <- factor(counts_long$condition)
#}

counts_long_inf <- cbind(counts_long_inf, cluster=as.factor(module_colors))
module_order <- unique(module_colors[gene_tree$order])

# uninfected
cpm_counts_uninf <- sweep(counts_uninf, 2, colSums(counts_uninf), '/') * 1E6
cpm_counts_uninf <- cpm_counts_uninf[rownames(cpm_counts_uninf) %in% gene_tree$labels,]

log2cpm_counts_uninf <- log2(cpm_counts_uninf + 1)
combined_gene_counts_uninf <- combine_replicates(log2cpm_counts_uninf, condition_uninf)

counts_long_uninf <- melt(combined_gene_counts_uninf, id.vars='row.names')

names(counts_long_uninf) <- c('gene_id', 'condition', 'expression')

# Human-readable labels
counts_long_uninf$condition <- mapping_uninf$to[match(counts_long_uninf$condition, mapping_uninf$from)]

# If non-numeric conditions (e.g. 'procyclic') are included, convert to
# factor and reorder levels of dataframe for better plotting
#if (!is.numeric(counts_long$condition)) {
#    counts_long$condition <- factor(counts_long$condition)
#}
counts_long_uninf <- cbind(counts_long_uninf, cluster=as.factor(module_colors))
```

```{r module_stats, results='asis'}
cat(sprintf("- Number of modules: %d\n", num_modules))
cat(sprintf("- Median module size: %0.1f\n", median(module_sizes$num_genes)))
cat(sprintf("- Largest module size: %d\n", max(module_sizes$num_genes)))
```

#### Functional Enrichment

```{r create_net_annotation_df}
# load relevant gene annotations and restore order
gene_info <- gene_info_orig %>% 
    filter(gene_id %in% rownames(diff)) %>%
    arrange(gene_id)

result <- cbind(gene_info, color=module_colors)
annot <- cbind(gene_info, color=module_colors, cluster=module_labels)
```

##### GO Enrichment

```{r child='../../../2015/00-shared/Rmd/results/go_enrichment_network.Rmd'}
```

##### KEGG Enrichment

```{r child='../../../2015/00-shared/Rmd/results/kegg_enrichment_network.Rmd'}
```

```{r child='02-kegg-enrichment-results.Rmd'}
```

##### CPDB Enrichment

```{r child='../../../2015/00-shared/Rmd/results/cpdb_enrichment_network.Rmd'}
```

```{r child='02-cpdb-enrichment-results.Rmd'}
```

##### TF regulon Enrichment

```{r child='../../../2015/00-shared/Rmd/results/hsapiens_marbach2016_tf_enrichment.Rmd'}
```

```{r child='02-tf-regulon-enrichment-results.Rmd'}
```

##### Visualization of enriched rewired subnetworks

```{r enriched_difference_subnetwork, results='asis', message=FALSE, fig.height=1600/192}
cat('\n')

for (module_color in unique(c(enriched_colors_go, enriched_colors_kegg,
                              enriched_colors_cpdb, enriched_colors_marbach))) {
    # show diff network
    genes <- (result %>% filter(color==module_color))$gene_id
    ind <- rownames(diff) %in% genes

    med_edge_weight <- median(diff[ind, ind])

    cat(sprintf("##### %s (median edge weight = %0.2f)\n", module_color, med_edge_weight))
    message(sprintf("%s\n", module_color))

    # create graph instance
    g <- graph.adjacency(diff[ind, ind], mode='undirected', weighted=TRUE)

    # get sum of edge weights for each vertex and rescale to range [-1, 1]
    edge_flux <- graph.strength(g)
    edge_flux <- edge_flux / max(abs(edge_flux))

    # color vertices based on net edge flux
    pal_neg <- colorRamp(c('purple', 'red'))
    pal_pos <- colorRamp(c('purple', 'blue'))

    V(g)$color <- sapply(edge_flux, FUN=function(x) {
        if (x < 0) {
            rgbcol <- pal_neg(abs(x))
        } else {
            rgbcol <- pal_pos(x)
        }
        rgb(rgbcol[1], rgbcol[2], rgbcol[3], 128, maxColorValue=255)
    })

    # color edges based on direction of change (red = neg, blue = pos)
    E(g)$color <- ifelse(E(g)$weight < 0, rgb(1,0,0,0.5), rgb(0,0,1,0.5))
    E(g)$weight <- abs(E(g)$weight)

    # remove low-weight edges (keep an average of 3 edges per node)
    num_edges <- 3 * length(V(g))

    if (num_edges < length(E(g))) {
        cutoff <- as.numeric(quantile(E(g)$weight, 1 - (num_edges / length(E(g)))))

        E(g)$weight[E(g)$weight < cutoff] <- 0

        # remove nodes and edges that become disconnected from pruning
        g <- delete.edges(g, which(E(g)$weight == 0))
        g <- delete.vertices(g, which(degree(g) == 0))
    }

    # relabel
    vlabels <- gene_info[match(names(V(g)), gene_info$gene_id),]$description

    # rescale edge weights 
    E(g)$weight <- E(g)$weight - min(E(g)$weight)
    E(g)$weight <- ((E(g)$weight / max(E(g)$weight))) * 5

    # remove any nodes or edges that become disconnected from scaling
    g <- delete.edges(g, which(E(g)$weight == 0))
    g <- delete.vertices(g, which(degree(g) == 0))

    layout_coords <- layout.fruchterman.reingold(g)

    V(g)$label.cex   <- 0.8
    V(g)$label.color <- '#333333'

    # network plot
    plot(g, layout=layout_coords, vertex.size=5, vertex.label=vlabels,
         vertex.label.dist=1,
         edge.width=E(g)$weight)

    # heatmap plot
    adj <- diff[ind,ind]

    # create diverging color ramp centered about 0 for heatmap
    # https://stackoverflow.com/questions/10985224/r-heatmap-with-diverging-colour-palette/10986203#10986203
    ncols <- 100
    ramp_cols <- colorRampPalette(colors=c('red', 'purple', 'blue'), space="Lab")(ncols)

    ## Make a vector with n+1 breaks
    ramp_breaks <- seq(-max(abs(adj)), max(adj), length.out=ncols+1)

    heatmap.2(adj, trace='none', dendrogram='row', cexRow=30/nrow(adj),
              labRow=gene_info$description[ind], margins=c(6, 18),
              labCol=FALSE, col=ramp_cols, breaks=ramp_breaks,
              key.title='', key.ylab='',  keysize=2, 
              key.xlab='Edge Weight\n (Infected - Uninfected)')

    # Normalize y-scales
    ylims <- c(0, max(max(counts_long_inf$expression), max(counts_long_uninf$expression)))

    cat('\n')
    print(module_profile_plot(counts_long_inf, module_color, line_color='#333333',
                              font_size=12, line_width=0.3, xlabel='Time (hrs)',
                              include_title=FALSE, ylimits=ylims,
                              white_background=TRUE))

    cat('\n')
    print(module_profile_plot(counts_long_uninf, module_color, line_color='#333333',
                              font_size=12, line_width=0.3, xlabel='Time (hrs)',
                              include_title=FALSE, ylimits=ylims,
                              white_background=TRUE))
    cat('\n')
}
```

```{r save_network, message=FALSE}
message("Saving difference network GraphML...")

# rescale edge weights to [-1, 1] and save network
#diff <- log1p(diff)
diff <- diff / max(abs(diff))

message("CURRENT DIR")
message(getwd())
outfile <- file.path('..', output_datadir, paste0('difference_network_', output_suffix, '.graphml'))

# annotations
annot <- cbind(gene_info, color=module_colors, cluster=module_labels)

g <- export_network_to_graphml(diff,
                               outfile,
                               threshold=0, max_edge_ratio=4,
                               nodeAttrDataFrame=annot)
```

```{r cleanup, include=FALSE}
rm(g, inf, uninf, distmat)
```

