```{r tf_enrichment_summary, results='asis'}
# get list of enriched TF regulons
enriched_tfs <- c()

for (x in names(module_coreg_enrichment)) {
    res <- module_coreg_enrichment[[x]]

    if (nrow(res) > 0) {
        tfs <- (res %>% filter(over_represented_pvalue_adj < 0.05))$category
        enriched_tfs <- unique(c(enriched_tfs, tfs))
    }
}

gene_tfs <- gene_tf_mapping %>% 
    filter(category %in% enriched_tfs & gene %in% gene_info$gene_id)

template <- paste('- Number of enriched TFs: %d/%d\n',
                  '- Number of genes associated with at least one enriched TF: %d/%d\n', sep='\n')
cat(sprintf(template,
            length(unique(gene_tfs$category)),
            length(unique(gene_tf_mapping$category)),
            length(unique(gene_tfs$gene)),
            nrow(gene_info)))
```

Histogram depicting the average number of KEGG pathways associated with each
gene, for all those genes annotated with at least one KEGG pathway.

```{r tf_enrichment_summary_ii}
# average number of TF's associated with each gene (only considering genes
# associated with at least one enriched TF...)
hist(table(gene_tfs$gene),
     xlab='# TF\'s associated with gene')

# collapse module tf enrichment results into a single dataframe and find the
# N TF's with the strongest enrichment
tf_enrich_df <- do.call("rbind", module_coreg_enrichment) %>%
    arrange(over_represented_pvalue_adj) %>%
    select(-starts_with('under'), -over_represented_pvalue) %>%
    head(5)
kable(tf_enrich_df)

# add one column for each of the top enriched TF's
for (cat in tf_enrich_df$category) {
    # create binary vector of enrichment status for specific TF
    gids <- (gene_tfs %>% 
        filter(category == cat))$gene
    annot[[cat]] <- annot$gene_id %in% gids
}
```
