```{r inf_vs_uninf_setup, results='asis'}
# keep only genes found in both uninfected and infected networks
common_genes <- intersect(rownames(uninf), rownames(inf))

cat(sprintf("- Keeping %d genes shared by infected (%d genes) and uninfected (%d genes) networks.\n",
            length(common_genes), nrow(inf), nrow(uninf)))

ind1 <- rownames(inf) %in% common_genes
ind2 <- rownames(uninf) %in% common_genes

inf   <- inf[ind1,ind1]
uninf <- uninf[ind2,ind2]

# reorder adjacency matrices
uninf <- uninf[rownames(inf), colnames(inf)]
```

```{r edge_weights_raw, fig.height=3.375}
par(mfrow=c(1,2), cex.main=1)
hist(inf, main="Raw Edge Weights (Infected)", xlab='Edge Weight')
hist(uninf, main="Raw Edge Weights (Uninfected)", xlab='Edge Weight')
```

In order to account for differences in correlation distributions due to
differences in replicate numbers, the edge weight distibutions for each matrix
will be quantile normalized.

```{r normalize_edge_weight_distibutions}
# create a data frame with one column per adjacency matrix
upper_tri <- upper.tri(inf)
lower_tri <- lower.tri(uninf)

mat <- cbind(
    inf[upper_tri],
    uninf[upper_tri]
)

# quantile normalize
mat <- normalize.quantiles(mat)

# replace original values
inf[upper_tri] <- mat[,1]
inf[lower_tri] <- t(inf)[lower_tri]

uninf[upper_tri] <- mat[,2]
uninf[lower_tri] <- t(uninf)[lower_tri]

rm(mat)
```

```{r edge_weights_normalized, fig.height=3.375}
par(mfrow=c(1,2), cex.main=1)
hist(inf, main="Normalized Edge Weights (Infected)", xlab='Edge Weight')
hist(uninf, main="Normalized Edge Weights (Uninfected)", xlab='Edge Weight')
```

