**Infected vs. Uninfected Difference Matrix**

```{r difference_heatmap, results='asis'}
diff <- inf - uninf

# sub-sample to speed up and better fit in display
ind <- sample(1:nrow(diff), 250)

# with legend
heatmap.2(diff[ind,ind], trace='none', dendrogram='row', labRow=FALSE, labCol=FALSE,
          col='plasma', main=sprintf('Difference Network\nAdjacency Matrix:\n%s', subtitle),
          margin=c(6, 6), density='none',
          key.title='', key.ylab='', keysize=2,
          key.xlab='Edge Weight\n (Infected - Uninfected)')

# without legend
#heatmap.2(diff[ind, ind], trace='none', dendrogram='row', labRow=FALSE, labCol=FALSE,
#          col='plasma', margin=c(6, 6),  key=FALSE)

# edge weight range
cat(sprintf('\n\n- Minimum edge weight: %0.3f\n', min(diff)))
cat(sprintf('\n- Maximum edge weight: %0.3f\n', max(diff)))
```

```{r diff_matrix_clustering}
# convert to distance matrix and perform hierarchical clustering
# take absolute value of difference adjacency matrix; sets of genes which are
# all changing direction together, will still be separated out
distmat <- (1 + diff) / 2

gene_tree <- flashClust(as.dist(distmat), method="average")
gene_tree$height <- round(gene_tree$height, 6)

# perform dynamic tree-cut based clustering
module_labels <- cutreeDynamicTree(dendro=gene_tree, deepSplit=FALSE, minModuleSize=10)

num_labels <- length(unique(module_labels))
pal <- c('grey', substring(rainbow(num_labels), 1, 7))
module_colors <- (pal[module_labels + 1])

module_mapping <- tbl_df(cbind(gene_id=rownames(diff), module=module_colors))

# create a mapping from module id to number of genes for later use
module_sizes <- setNames(as.data.frame(module_colors), 'module_id') %>% 
    group_by(module_id) %>% 
    summarize(num_genes=n())

num_modules <- length(unique(module_colors))
```

```{r generate_long_counts}
# cpm-transform raw counts (infected)
cpm_counts_inf <- sweep(counts_inf, 2, colSums(counts_inf), '/') * 1E6
cpm_counts_inf <- cpm_counts_inf[rownames(cpm_counts_inf) %in% gene_tree$labels,]

log2cpm_counts_inf <- log2(cpm_counts_inf + 1)

combined_gene_counts_inf <- combine_replicates(log2cpm_counts_inf,
                                               condition_inf)
counts_long_inf <- melt(combined_gene_counts_inf, id.vars='row.names')
names(counts_long_inf) <- c('gene_id', 'condition', 'expression')

# Human-readable labels
counts_long_inf$condition <- mapping_inf$to[match(counts_long_inf$condition, mapping_inf$from)]

# If non-numeric conditions (e.g. 'procyclic') are included, convert to
# factor and reorder levels of dataframe for better plotting
#if (!is.numeric(counts_long$condition)) {
#    counts_long$condition <- factor(counts_long$condition)
#}

counts_long_inf <- cbind(counts_long_inf, cluster=as.factor(module_colors))
module_order <- unique(module_colors[gene_tree$order])

# uninfected
cpm_counts_uninf <- sweep(counts_uninf, 2, colSums(counts_uninf), '/') * 1E6
cpm_counts_uninf <- cpm_counts_uninf[rownames(cpm_counts_uninf) %in% gene_tree$labels,]

log2cpm_counts_uninf <- log2(cpm_counts_uninf + 1)
combined_gene_counts_uninf <- combine_replicates(log2cpm_counts_uninf, condition_uninf)

counts_long_uninf <- melt(combined_gene_counts_uninf, id.vars='row.names')

names(counts_long_uninf) <- c('gene_id', 'condition', 'expression')

# Human-readable labels
counts_long_uninf$condition <- mapping_uninf$to[match(counts_long_uninf$condition, mapping_uninf$from)]

# If non-numeric conditions (e.g. 'procyclic') are included, convert to
# factor and reorder levels of dataframe for better plotting
#if (!is.numeric(counts_long$condition)) {
#    counts_long$condition <- factor(counts_long$condition)
#}
counts_long_uninf <- cbind(counts_long_uninf, cluster=as.factor(module_colors))
```

```{r module_stats, results='asis'}
cat(sprintf("- Number of modules: %d\n", num_modules))
cat(sprintf("- Median module size: %0.1f\n", median(module_sizes$num_genes)))
cat(sprintf("- Largest module size: %d\n", max(module_sizes$num_genes)))
```

```{r create_net_annotation_df}
# load relevant gene annotations and restore order
gene_info <- gene_info_orig %>% 
    filter(gene_id %in% rownames(diff)) %>%
    arrange(gene_id)

result <- cbind(gene_info, color=module_colors)
annot <- cbind(gene_info, color=module_colors, cluster=module_labels)
```

```{r child='../../../2015/00-shared/Rmd/results/go_enrichment_network.Rmd'}
```

```{r child='../../../2015/00-shared/Rmd/results/kegg_enrichment_network.Rmd'}
```

```{r child='04-kegg-enrichment-results.Rmd'}
```

```{r child='../../../2015/00-shared/Rmd/results/cpdb_enrichment_network.Rmd'}
```

```{r child='04-cpdb-enrichment-results.Rmd'}
```

```{r child='../../../2015/00-shared/Rmd/results/hsapiens_marbach2016_tf_enrichment.Rmd'}
```

```{r child='04-tf-regulon-enrichment-results.Rmd'}
```

### Visualization of enriched rewired subnetworks

```{r enriched_difference_subnetwork, results='asis', message=FALSE}
cat('\n')

for (module_color in unique(c(enriched_colors_go, enriched_colors_kegg,
                              enriched_colors_cpdb, enriched_colors_marbach))) {
    # show diff network
    genes <- (result %>% filter(color==module_color))$gene_id
    ind <- rownames(diff) %in% genes

    # diff subnetwork
    diff_subnet <- diff[ind, ind]

    min_edge_weight <- min(diff_subnet)
    max_edge_weight <- max(diff_subnet)
    med_edge_weight <- median(diff_subnet)

    cat(sprintf("#### %s (median edge weight = %0.2f, min = %0.2f, max = %0.2f)\n", 
                module_color, med_edge_weight, min_edge_weight, max_edge_weight))
    message(sprintf("%s\n", module_color))

    # create graph instance
    g <- graph.adjacency(diff_subnet, mode='undirected', weighted=TRUE)

    # get sum of edge weights for each vertex and rescale to range [-1, 1]
    # edge flux distribution can have a long tail, so we log it first.
    edge_flux <- graph.strength(g)
    edge_flux <- sign(edge_flux) * log1p(abs(edge_flux))
    edge_flux <- edge_flux / max(abs(edge_flux))

    # color vertices based on net edge flux
    pal_neg <- colorRamp(c('purple', 'red'))
    pal_pos <- colorRamp(c('purple', 'blue'))

    V(g)$color <- sapply(edge_flux, FUN=function(x) {
        if (x < 0) {
            rgbcol <- pal_neg(abs(x))
        } else {
            rgbcol <- pal_pos(x)
        }
        rgb(rgbcol[1], rgbcol[2], rgbcol[3], 128, maxColorValue=255)
    })

    # color edges based on direction of change (red = neg, blue = pos)
    E(g)$color <- ifelse(E(g)$weight < 0, rgb(1,0,0,0.5), rgb(0,0,1,0.5))

    # to separate groups of genes that are becoming more tightly co-expressed
    # together from those that are becoming deregulated for igraph plot,
    # use correlation of diff values instead of diff values themselves;
    # this way genes with strong pos or neg diffs can have high edge weight
    # values while genes across will have lower ones...
    #
    # to do this, we will create a second graph with edge weights equal
    # to the correlations between genes, and apply the same filtering steps
    # as we do to original graph.
    #

    # 2017/12/07 - disabling for now; will come back to this approach in
    # the future if time allows...
    #cor_subnet <- cor(diff_subnet)

    # ensure same edges are included
    #cor_subnet[diff_subnet == 0] <- 0

    #g2 <- graph.adjacency(cor_subnet, mode='undirected', weighted=TRUE)

    # remove low-weight edges (keep an average of 2.5 edges per node)
    num_edges <- 2.5 * length(V(g))

    if (num_edges < length(E(g))) {
        cutoff <- as.numeric(quantile(abs(E(g)$weight), 
                                      1 - (num_edges / length(E(g)))))

        mask <- abs(E(g)$weight) < cutoff

        #E(g)$weight[mask] <- 0
        #E(g2)$weight[mask] <- 0

        # remove nodes and edges that become disconnected from pruning
        g <- delete.edges(g, which(E(g)$weight == 0))
        g <- delete.vertices(g, which(degree(g) == 0))

        #g2 <- delete.edges(g2, which(E(g2)$weight == 0))
        #g2 <- delete.vertices(g2, which(degree(g2) == 0))
    }

    # relabel
    vlabels <- gene_info[match(names(V(g)), gene_info$gene_id),]$description

    # keep track of edge weight sign and convert to all positive values
    edge_sign <- sign(E(g)$weight)

    # Negative weights are treated are treated at non-edges by igraph, and
    # would not be displayed. 
    E(g)$weight <- abs(E(g)$weight)

    # log and rescale edge weights 
    E(g)$weight <- log1p(E(g)$weight)
    E(g)$weight <- E(g)$weight - min(E(g)$weight)
    E(g)$weight <- ((E(g)$weight / max(E(g)$weight))) * 4

    # remove any nodes or edges that become disconnected from scaling
    g <- delete.edges(g, which(E(g)$weight == 0))
    g <- delete.vertices(g, which(degree(g) == 0))

    layout_coords <- layout.fruchterman.reingold(g)

    # TEMP WORK-AROUND FOR FIGURE (2017/12/02)
    # DEAD-Box helicase 10 only has one extremely low-weight edge; skews
    # the plot layout..
    #if (module_color == "#00FF77") {
    #    g <- delete.vertices(g, "ENSG00000178105")
    #}
    V(g)$label.cex   <- 0.3
    V(g)$label.color <- '#333333'

    # network plot
    plot(g, layout=layout_coords, vertex.size=3, vertex.label=vlabels,
         vertex.label.dist=1,
         edge.width=E(g)$weight)

    # heatmap plot
    adj <- diff[ind,ind]

    # create diverging color ramp centered about 0 for heatmap
    # https://stackoverflow.com/questions/10985224/r-heatmap-with-diverging-colour-palette/10986203#10986203
    ncols <- 100
    ramp_cols <- colorRampPalette(colors=c('red', 'purple', 'blue'), space="Lab")(ncols)

    ## Make a vector with n+1 breaks
    ramp_breaks <- seq(-max(abs(adj)), max(adj), length.out=ncols+1)

    gene_labels <- gene_info$description[ind]
    gene_ids    <- gene_info$gene_id[ind]
    gene_labels[is.na(gene_labels)] <- gene_ids[is.na(gene_labels)] 

    # diff heatmap
    heatmap.2(adj, trace='none', dendrogram='row', cexRow=30/nrow(adj),
              #labRow=gene_labels, margins=c(8, 24),
              labRow=gene_labels, margins=c(4, 6),
              labCol=FALSE, col=ramp_cols, breaks=ramp_breaks,
              symm=TRUE, symkey=TRUE, symbreaks=TRUE,
              key.title='', key.ylab='',  keysize=2, 
              key.xlab='Edge Weight\n (Infected - Uninfected)')

    # inf heatmap
    #heatmap.2(inf[ind, ind], trace='none', dendrogram='row', cexRow=30/nrow(adj),
    #          labRow=gene_labels, margins=c(8, 20),
    #          labCol=FALSE, col=ramp_cols, breaks=ramp_breaks,
    #          key.title='', key.ylab='',  keysize=2, 
    #          key.xlab='Edge Weight\n (Infected)')

    ## uninf heatmap
    #heatmap.2(uninf[ind, ind], trace='none', dendrogram='row', cexRow=30/nrow(adj),
    #          labRow=gene_labels, margins=c(8, 20),
    #          labCol=FALSE, col=ramp_cols, breaks=ramp_breaks,
    #          key.title='', key.ylab='',  keysize=2, 
    #          key.xlab='Edge Weight\n (Infected)')

    cat('\n')
}
```

### Expression plots for enriched rewired subnetworks

```{r, fig.height=3, results='asis'}
# Iterating over same modules and printing line expression plots;
# separated from above chunk to allow for different dimensions to be used
par(mfrow=(c(1,2)))

for (module_color in unique(c(enriched_colors_go, enriched_colors_kegg,
                              enriched_colors_cpdb, enriched_colors_marbach))) {

    cat(sprintf("\n\n#### %s\n\n", module_color))

    # Normalize y-scales
    ylims <- c(0, max(max(counts_long_inf$expression), max(counts_long_uninf$expression)))

    # uninfected expression plot
    p1 <- module_profile_plot(counts_long_uninf, module_color, line_color='#333333',
                              line_width=0.4, xlabel='Time (hrs)',
                              include_title=FALSE, ylimits=ylims) +
        ggtitle('Uninfected') +
        theme_bw_high_res() +
        theme(axis.text.x=element_text(angle=MANUSCRIPT_CONFIG$xanglexangle, 
                                       hjust=MANUSCRIPT_CONFIG$xhjust,
                                       size=9, lineheight=0.9)) +
        theme()

    # infected expression plot
    p2 <- module_profile_plot(counts_long_inf, module_color, line_color='#333333',
                               line_width=0.4, xlabel='Time (hrs)',
                               include_title=FALSE, ylimits=ylims) +
        ggtitle('Infected') +
        theme_bw_high_res() +
        theme(axis.text.x=element_text(angle=MANUSCRIPT_CONFIG$xanglexangle, 
                                       hjust=MANUSCRIPT_CONFIG$xhjust,
                                       size=9, lineheight=0.9)) +

    grid.arrange(p1, p2, ncol=2)
}
```

```{r save_network, message=FALSE}
message("Saving difference network GraphML...")

# rescale edge weights to [-1, 1] and save network
#diff <- log1p(diff)
diff_scaled <- diff / max(abs(diff))

message("CURRENT DIR")
message(getwd())
outfile <- file.path('..', output_datadir, paste0('difference_network_', output_suffix, '.graphml'))

# annotations
annot <- cbind(gene_info, color=module_colors, cluster=module_labels)

g <- export_network_to_graphml(diff_scaled,
                               outfile,
                               threshold=0, max_edge_ratio=4,
                               nodeAttrDataFrame=annot)
```

```{r cleanup, include=FALSE}
rm(g, inf, uninf, distmat)
```

